# Generated by Django 2.1.13 on 2019-10-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bt',
            fields=[
                ('id_bt', models.IntegerField(db_column='ID_bt', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20)),
            ],
            options={
                'db_table': 'BT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id_city', models.IntegerField(db_column='ID_city', primary_key=True, serialize=False)),
                ('city', models.CharField(db_column='City', max_length=20)),
            ],
            options={
                'db_table': 'Cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupindicators',
            fields=[
                ('id_group', models.IntegerField(db_column='ID_group', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=30)),
            ],
            options={
                'db_table': 'GroupIndicators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id_indicator', models.IntegerField(db_column='ID_indicator', primary_key=True, serialize=False)),
                ('indicator', models.CharField(db_column='Indicator', max_length=30)),
            ],
            options={
                'db_table': 'Indicators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id_office', models.IntegerField(db_column='ID_office', primary_key=True, serialize=False)),
                ('office', models.IntegerField(db_column='Office')),
            ],
            options={
                'db_table': 'Offices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valuebase',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('value', models.IntegerField(db_column='Value')),
            ],
            options={
                'db_table': 'ValueBase',
                'managed': False,
            },
        ),
    ]

